# Generated by Django 5.1.5 on 2026-09-12 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0010_recorrido_marcapersona'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumenDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(auto_now_add=True)),
                ('total_visitors', models.IntegerField(default=0)),
                ('metrica_principal', models.CharField(blank=True, default='', max_length=80)),
                ('valor', models.FloatField(default=0.0)),
                ('negocio', models.CharField(blank=True, default='', max_length=80)),
                ('camera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cameras.camera')),
            ],
            options={
                'db_table': 'resumen_dia',
            },
        ),
    ]
