# Generated by Django 5.1.5 on 2026-08-13 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('long_queue', 'Fila larga'), ('empty_counter', 'Caja desatendida'), ('overcrowding', 'Aforo excedido')], max_length=30)),
                ('zone_name', models.CharField(max_length=80)),
                ('value', models.FloatField(help_text='Valor que disparó el evento (personas, segundos)')),
                ('occurred_at', models.DateTimeField()),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cameras.camera')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='EventClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='clips/%Y/%m/%d/')),
                ('expires_at', models.DateTimeField()),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clip', to='analytics.event')),
            ],
        ),
        migrations.CreateModel(
            name='MetricWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=80)),
                ('zone_kind', models.CharField(max_length=20)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('occupancy_avg', models.FloatField()),
                ('occupancy_max', models.IntegerField()),
                ('dwell_seconds', models.FloatField()),
                ('unique_visitors', models.IntegerField()),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='cameras.camera')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['camera', 'started_at'], name='analytics_m_camera__30c7ba_idx')],
            },
        ),
    ]
