# Generated by Django 5.1.5 on 2026-08-14 12:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('terminado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('ok', models.BooleanField(default=True)),
                ('detalle', models.TextField(blank=True, default='')),
            ],
        ),
    ]
