# Generated by Django 5.1.5 on 2026-08-14 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_jobrun'),
        ('tenancy', '0002_business_comparte_corpus'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('long_queue', 'Fila larga'), ('empty_counter', 'Caja desatendida'), ('overcrowding', 'Aforo excedido'), ('camara_caida', 'Cámara sin señal')], max_length=30)),
                ('canal', models.CharField(choices=[('webhook', 'Webhook'), ('email', 'Email')], default='webhook', max_length=10)),
                ('destino', models.CharField(help_text='URL del webhook.', max_length=300)),
                ('minutos_silencio', models.IntegerField(default=15)),
                ('ultima_notificacion', models.DateTimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='tenancy.business')),
            ],
        ),
        migrations.CreateModel(
            name='AlertDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('resultado', models.CharField(max_length=12)),
                ('error', models.TextField(blank=True, default='')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='analytics.alertrule')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
