# Generated by Django 5.1.5 on 2026-08-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alertrule_alertdelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricwindow',
            name='degradada',
            field=models.BooleanField(default=False),
        ),
    ]
