# Generated by Django 5.1.5 on 2026-08-15 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_metricwindow_degradada'),
        ('cameras', '0006_countingline'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossingWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_name', models.CharField(max_length=80)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('entradas', models.IntegerField(default=0)),
                ('salidas', models.IntegerField(default=0)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crossings', to='cameras.camera')),
            ],
            options={
                'indexes': [models.Index(fields=['camera', 'started_at'], name='analytics_c_camera__0d333b_idx')],
            },
        ),
    ]
