# Generated by Django 5.1.5 on 2026-09-07 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_trajectory'),
        ('cameras', '0010_recorrido_marcapersona'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeatmapWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('grid_rows', models.IntegerField()),
                ('grid_cols', models.IntegerField()),
                ('counts', models.JSONField(help_text='Matriz filas x columnas de pisadas por celda.')),
                ('personas', models.IntegerField(default=0, help_text='Track ids distintos vistos en esta ventana. No dedupe entre ventanas: alguien que cruza el límite de una ventana a otra puede contarse dos veces. Aproximación aceptada, no un bug escondido.')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heatmaps', to='cameras.camera')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['camera', 'started_at'], name='analytics_h_camera__0050cf_idx')],
            },
        ),
    ]
