# Generated by Django 5.1.5 on 2026-09-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_heatmapwindow'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertrule',
            name='umbral',
            field=models.FloatField(blank=True, help_text='A partir de cuánto avisar, en la unidad del tipo de aviso (segundos de espera, personas). Vacío = el del rubro.', null=True),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='tipo_evento',
            field=models.CharField(choices=[('long_queue', 'Fila larga'), ('empty_counter', 'Caja desatendida'), ('overcrowding', 'Aforo excedido'), ('crowded_queue', 'Fila con mucha gente'), ('camara_caida', 'Cámara sin señal')], max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='kind',
            field=models.CharField(choices=[('long_queue', 'Fila larga'), ('empty_counter', 'Caja desatendida'), ('overcrowding', 'Aforo excedido'), ('crowded_queue', 'Fila con mucha gente')], max_length=30),
        ),
    ]
