# Generated by Django 5.1.5 on 2026-10-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_alertrule_umbral'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertdelivery',
            name='camara',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='alertdelivery',
            name='simulado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='accion',
            field=models.CharField(choices=[('avisar', 'Avisarme'), ('abrir_caja', 'Pedir que abran la segunda caja'), ('mensaje_personal', 'Mandar mensaje al personal'), ('registrar', 'Registrar en el reporte')], default='avisar', max_length=20),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='texto',
            field=models.CharField(blank=True, default='', help_text='Mensaje propio para las acciones operativas.', max_length=200),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='destino',
            field=models.CharField(blank=True, default='', help_text='URL del webhook o correo.', max_length=300),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='tipo_evento',
            field=models.CharField(choices=[('long_queue', 'Fila larga'), ('empty_counter', 'Caja desatendida'), ('overcrowding', 'Aforo excedido'), ('crowded_queue', 'Fila con mucha gente'), ('entry_peak', 'Pico de entradas'), ('low_traffic', 'Poco tráfico en una zona'), ('camara_caida', 'Cámara sin señal')], max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='kind',
            field=models.CharField(choices=[('long_queue', 'Fila larga'), ('empty_counter', 'Caja desatendida'), ('overcrowding', 'Aforo excedido'), ('crowded_queue', 'Fila con mucha gente'), ('entry_peak', 'Pico de entradas'), ('low_traffic', 'Poco tráfico en una zona')], max_length=30),
        ),
    ]
