# Generated by Django 5.1.5 on 2026-08-14 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('body', models.TextField()),
                ('model', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='tenancy.business')),
            ],
            options={
                'ordering': ['-day'],
                'unique_together': {('business', 'day')},
            },
        ),
    ]
