# Generated by Django 5.1.5 on 2026-08-14 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpusEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohorte', models.CharField(db_index=True, help_text='Tipo de negocio: cafe, restaurant, retail...', max_length=20)),
                ('huella', models.CharField(db_index=True, max_length=16)),
                ('day', models.DateField()),
                ('visitantes', models.IntegerField()),
                ('aforo_pico', models.IntegerField()),
                ('espera_fila_seg', models.FloatField(blank=True, null=True)),
                ('cobertura_personal', models.FloatField(blank=True, null=True)),
                ('hora_pico', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['cohorte', 'day'], name='insights_co_cohorte_779145_idx')],
                'unique_together': {('huella', 'day')},
            },
        ),
    ]
