# Generated by Django 5.1.5 on 2026-08-14 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='comparte_corpus',
            field=models.BooleanField(default=True, help_text='Si está activo, las métricas anónimas de este negocio alimentan el corpus comparativo. No afecta su capacidad de consultarlo.'),
        ),
    ]
