# Generated by Django 5.1.5 on 2026-08-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0003_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentoLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=150)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('exito', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['identificador', 'creado'], name='tenancy_int_identif_cfe8fc_idx')],
            },
        ),
    ]
