# Generated by Django 5.1.5 on 2026-08-15 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0004_intentologin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('max_camaras', models.IntegerField(default=1)),
                ('retencion_dias', models.IntegerField(default=90)),
                ('precio_centavos', models.IntegerField(default=0, help_text='Interfaz de cobro; sin facturación real todavía.')),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='Sin plan aplica el límite por defecto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to='tenancy.plan'),
        ),
    ]
