# Generated by Django 5.1.5 on 2026-08-15 09:10

import django.db.models.deletion
import tenancy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0005_plan_business_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Dueño'), ('admin', 'Administrador')], default='owner', max_length=10)),
                ('token', models.CharField(default=tenancy.models._token_invitacion, max_length=64, unique=True)),
                ('aceptada', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='tenancy.business')),
            ],
        ),
    ]
