# Generated by Django 5.1.5 on 2026-09-09 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0006_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='abre',
            field=models.TimeField(default=datetime.time(0, 0), help_text='Hora a la que abre el local. Igual a la de cierre = avisar a cualquier hora.'),
        ),
        migrations.AddField(
            model_name='business',
            name='cierra',
            field=models.TimeField(default=datetime.time(0, 0), help_text='Hora a la que cierra. Fuera de este rango no se manda ningún aviso, aunque el evento sí se registre.'),
        ),
    ]
