# Generated by Django 5.1.5 on 2026-08-13 22:56

import cameras.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('source', models.CharField(default='0', max_length=300)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='tenancy.business')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('kind', models.CharField(choices=[('general', 'General (aforo)'), ('queue', 'Fila / espera'), ('counter', 'Caja / mostrador'), ('staff', 'Área de personal')], default='general', max_length=20)),
                ('polygon', models.JSONField(validators=[cameras.models.validate_polygon])),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='cameras.camera')),
            ],
        ),
    ]
