# Generated by Django 5.1.5 on 2026-08-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='credencial_cifrada',
            field=models.BinaryField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='camera',
            name='credencial_usuario',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
