# Generated by Django 5.1.5 on 2026-08-14 07:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_camera_credencial_cifrada_camera_credencial_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_latido', models.DateTimeField(default=django.utils.timezone.now)),
                ('frames_leidos', models.IntegerField(default=0)),
                ('reconexiones', models.IntegerField(default=0)),
                ('ultimo_error', models.TextField(blank=True, default='')),
                ('camera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salud', to='cameras.camera')),
            ],
        ),
    ]
