# Generated by Django 5.1.5 on 2026-08-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_camerahealth'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='frame_h',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='camera',
            name='frame_w',
            field=models.IntegerField(default=0),
        ),
    ]
