# Generated by Django 5.1.5 on 2026-08-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0004_camera_frame_h_camera_frame_w'),
    ]

    operations = [
        migrations.AddField(
            model_name='camerahealth',
            name='fps_medido',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='camerahealth',
            name='frames_descartados',
            field=models.IntegerField(default=0),
        ),
    ]
