# Generated by Django 5.1.5 on 2026-08-14 23:18

import cameras.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0005_camerahealth_fps_medido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('puntos', models.JSONField(validators=[cameras.models.validate_line])),
                ('invertir', models.BooleanField(default=False, help_text='Intercambia entrada y salida.')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='cameras.camera')),
            ],
        ),
    ]
