# Generated by Django 5.1.5 on 2026-08-15 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0006_countingline'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='altura_camara_m',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='camera',
            name='angulo_grados',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='camera',
            name='lost_track_buffer',
            field=models.IntegerField(default=30, help_text='Frames que un track sobrevive a una oclusión.'),
        ),
        migrations.AddField(
            model_name='camera',
            name='zona_muerta',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
