# Generated by Django 5.1.5 on 2026-08-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0007_camera_altura_camara_m_camera_angulo_grados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='contexto',
            field=models.CharField(blank=True, choices=[('general', 'General (aforo)'), ('queue', 'Fila / espera'), ('counter', 'Caja / mostrador'), ('staff', 'Área de personal'), ('entrada', 'Entrada / acceso'), ('pasillo', 'Pasillo'), ('escaleras', 'Escaleras eléctricas'), ('comidas', 'Patio de comidas'), ('parqueadero', 'Parqueadero')], default='general', help_text='A qué apunta la cámara. Sus zonas lo heredan si no traen el suyo.', max_length=20),
        ),
        migrations.AlterField(
            model_name='zone',
            name='kind',
            field=models.CharField(blank=True, choices=[('general', 'General (aforo)'), ('queue', 'Fila / espera'), ('counter', 'Caja / mostrador'), ('staff', 'Área de personal'), ('entrada', 'Entrada / acceso'), ('pasillo', 'Pasillo'), ('escaleras', 'Escaleras eléctricas'), ('comidas', 'Patio de comidas'), ('parqueadero', 'Parqueadero')], default='general', help_text='Vacío = hereda el contexto de la cámara.', max_length=20),
        ),
    ]
