# Generated by Django 5.1.5 on 2026-09-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0008_camera_contexto_alter_zone_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='descripcion',
            field=models.CharField(blank=True, default='', help_text='Qué se ve en el video. La propone el asistente de IA y se puede corregir.', max_length=300),
        ),
    ]
