# Generated by Django 5.1.5 on 2026-09-07 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0009_camera_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recorrido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pistas', models.JSONField(default=list)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('camera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recorrido', to='cameras.camera')),
            ],
        ),
        migrations.CreateModel(
            name='MarcaPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.IntegerField()),
                ('es_personal', models.BooleanField(default=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcas_persona', to='cameras.camera')),
            ],
            options={
                'unique_together': {('camera', 'track_id')},
            },
        ),
    ]
