"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(k&xvqqduh7f=k7knfstq8+f)$l9@6q+5b(3v_vx1x1e_8&595'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'tenancy',
    'cameras',
    'analytics',
    'vision',
    'insights',
    'dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'tenancy.sin_cuenta.sin_cuenta',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
# Donde collectstatic deja los archivos y de donde los sirve nginx
# (deploy/nginx/*.conf apunta aquí). Está en .gitignore: se regenera en cada
# despliegue, no se versiona.
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

import os
from dotenv import load_dotenv

from config.dburl import parse_database_url
from config.entorno import ajustes_tls, hosts_permitidos

load_dotenv(BASE_DIR / ".env")

SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "dev-insecure-key")
DEBUG = os.getenv("DJANGO_DEBUG", "False") == "True"
ALLOWED_HOSTS = hosts_permitidos(os.getenv("DJANGO_ALLOWED_HOSTS", ""))
TLS = os.getenv("DJANGO_TLS", "False") == "True"

DATABASE_URL = os.getenv("DATABASE_URL", "")
DATABASES = {"default": parse_database_url(DATABASE_URL, BASE_DIR)}

DETECTOR_MODEL = os.getenv("DETECTOR_MODEL", "yolov8n.pt")
DETECTOR_IMGSZ = int(os.getenv("DETECTOR_IMGSZ", "640"))
DETECTOR_DEVICE = os.getenv("DETECTOR_DEVICE", "cpu")
# Con carga ajena en CPU, 4 hilos de torch en 4 nucleos se pisan: 1.3 s por
# inferencia contra 0.16 s con 2. Debe fijarse antes de importar torch.
os.environ.setdefault("OMP_NUM_THREADS", "2")
SAMPLE_FPS = float(os.getenv("SAMPLE_FPS", "2"))
LLM_MODEL = os.getenv("LLM_MODEL", "claude-haiku-4-5-20251001")
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY", "")
CLIP_RETENTION_DAYS = int(os.getenv("CLIP_RETENTION_DAYS", "30"))
MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

# Correo de los avisos. Sin SMTP configurado el aviso se imprime en el log en
# vez de perderse: se ve que el sistema quiso avisar, y de qué.
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND",
                          "django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "avisos@vision-analytics.local")

# Carpetas desde las que se permite servir un archivo de video al editor.
# `Camera.source` es una ruta libre: sin este cerco, la vista sería un lector
# de cualquier archivo del servidor.
VIDEO_ROOTS = [str(BASE_DIR), str(MEDIA_ROOT)]

# Rama sin-cuenta: entra directo al dashboard (SIN_CUENTA=0 para exigir login).
SIN_CUENTA = os.getenv("SIN_CUENTA", "1") == "1"

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/accounts/login/"

AUTHENTICATION_BACKENDS = ["tenancy.lockout.LockoutModelBackend"]

SESSION_COOKIE_HTTPONLY = True
# False a propósito: el panel (SPA) lee la cookie para mandar X-CSRFToken. Con True
# el JS no la ve y todo POST/PUT/DELETE del panel responde 403. La sesión sigue HttpOnly.
CSRF_COOKIE_HTTPONLY = False
SESSION_COOKIE_AGE = 60 * 60 * 8          # 8 horas
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

if not DEBUG:
    # Lo que se enciende depende de si hay certificado, no de DEBUG: ver
    # config/entorno.py. globals() porque son settings de módulo, no un dict.
    globals().update(ajustes_tls(TLS, ALLOWED_HOSTS))

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "redactor": {"()": "config.logging_filters.RedactorDeCredenciales"},
        "request_id": {"()": "config.logging_filters.RequestIdFilter"},
    },
    "formatters": {
        "operacion": {"format": "%(asctime)s %(levelname)s [%(request_id)s] %(name)s %(message)s"},
    },
    "handlers": {
        "consola": {
            "class": "logging.StreamHandler",
            "filters": ["request_id", "redactor"],
            "formatter": "operacion",
        },
    },
    "root": {"handlers": ["consola"], "level": "INFO"},
}
